### ISSUE TITLE
BBSwitch won't disable after restarting kernel

### ISSUE THREAD

**Issue by sentiono** [Bumblebee-Project/bbswitch#51] opened 2013-03-20 06:11 UTC
In reference to Bumblebee-Project/bbswitch/issues/46 and Bumblebee-Project/Bumblebee#358, I would like to add few things.

Thank you to make bbswitch work with 3.8.x and I can confirm that.
There is some notes that need to be aware off.

After upgrading kernel or rebooting different kernel, bbswitch would run fine and able to turn off the nvidia/discrete graphics without any issue.
However, if we are rebooting the computer on the same kernel, bbswitch would not be able to turn the discrete card off.

I have tested this from 3.8.3-201 to the latest one 3.8.3-203.
I noticed that if I reboot on same kernel more than once, 3.8.3-203, the nvidia module will fail to compile, as such bumblebeed will fail to start, causing bbswitch losing ability to switch off the discrete card.

Working around this, reboot to 3.8.3-201, bbswitch will be working fine (cause nvidia module can be compiled ok and bumblebeed started). Turn off. Then reboot again to 3.8.3-203 to allow recompilation of nvidia modules.
But should it be the way?

If any of you need the test output, I will email you separately because it's kind of long.

In addition, once the bbswitch is on (ie. optirun glxspheres), it can't be turned off even the application is already exited, so restarting is the only option.

Thanks.

**Comment by ArchangeGabriel** [comment] 2015-12-27 15:10
I’m closing this, the issue is old and several things involved do not exists in the code anymore. If you’re still having an issue, please open a new thread with the accurate logs and description.

**Closed by ArchangeGabriel** 2015-12-27 15:10 UTC
