### ISSUE TITLE
Eurocom M5 Pro draining 40% of battery per hour while suspended to ram

### ISSUE THREAD

**Issue by JeorgeMatt** [Bumblebee-Project/bbswitch#129] opened 2016-03-31 06:32 UTC
I recently decided to use Ubuntu as my main OS in Eurocom M5 Pro, but I have noticed something strange with bbswitch.
After installing it is draining a way too much battery while suspended to run. In windows or without bbswitch it uses about 3% per hour.
Everything is working perfectly but the system is impossible to use as a laptop since the suspend to ram  does not last very long and the hibernation is unreliable.

Is there any fix for this?

**Comment by oanonymos0** [comment] 2016-04-04 13:44
having an open OpenGL program on nvidia before suspend may help.

**Comment by Lekensteyn** [comment] 2016-04-06 12:12
I think this is a duplicate of #115, if not please let me know.

**Closed by Lekensteyn** 2016-04-06 12:12 UTC

**Comment by JeorgeMatt** [comment] 2016-04-06 20:37
It is a different laptop and i'm not sure if it is the same problem
