### ISSUE TITLE
Unable to use bumblebee on 740m

### ISSUE THREAD

**Issue by vadi2** [Bumblebee-Project/bbswitch#85] opened 2014-01-18 06:48 UTC
I'm unable to get Bumblebee to work on Toshiba L50 A006 using Ubuntu 13.10. The stock 3.11 kernel did not seem to work for any nvidia drivers - always running into the "NVRM: failed to copy vbios to system memory." error. I read that the 3.11 kernel had an issue and that the 3.12 kernel fixes it, so I've installed 3.12-rc3 - but now no nvidia kernel module builds, not even 331.20 from the xorg-edgers fresh X crack PPA. Without a module, the drivers of course won't work.

Is there a solution to this circular dependency?

**Comment by ArchangeGabriel** [comment] 2015-12-27 15:23
Closing, old and probable duplicate of https://github.com/Bumblebee-Project/bbswitch/issues/80.

**Closed by ArchangeGabriel** 2015-12-27 15:23 UTC
