### ISSUE TITLE
bbswitch does not work on Nvidia GT750M

### ISSUE THREAD

**Issue by goldhoorn** [Bumblebee-Project/bbswitch#92] opened 2014-02-27 21:55 UTC
I'm Running a Ubuntu 12.04 On a Dell Inspirion 15 7537

The result from modprobe/dmesg:

[  559.534624] bbswitch: version 0.8
[  559.534632] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[  559.534639] bbswitch: Found discrete VGA device 0000:04:00.0: \_SB_.PCI0.RP05.PXSX
[  559.534651] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  559.534657] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  559.534706] bbswitch: No suitable _DSM call found.

lspci -v:

04:00.0 3D controller: NVIDIA Corporation GK107M [GeForce GT 750M] (rev a1)
	Subsystem: Dell Device 05fa
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at e2000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at e0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 3000 [size=128]
	Expansion ROM at <ignored> [disabled]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Endpoint, MSI 00
	Capabilities: [b4] Vendor Specific Information: Len=14 <?>
	Capabilities: [100] Virtual Channel
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Capabilities: [900] #19
	Kernel driver in use: nvidia
	Kernel modules: nvidia_304, nouveau, nvidiafb

...
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Dell Device 05fa
	Flags: bus master, fast devsel, latency 0, IRQ 61
	Memory at e3000000 (64-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915

I'm a Computer scientist, so ping me if you need additional help...

**Comment by ArchangeGabriel** [comment] 2015-12-27 15:26
Closing, old and probable dupe of https://github.com/Bumblebee-Project/bbswitch/issues/80.

**Closed by ArchangeGabriel** 2015-12-27 15:26 UTC
